version: '3.8'
services:
#  splunk:
#    image: splunk/splunk:latest
#    container_name: splunk
#    environment:
#      - SPLUNK_START_ARGS=--accept-license
#      - SPLUNK_PASSWORD=changed!
#    ports:
#      - 8000:8000
#      - 5555:5555
#      - 8088:8088
#      - 8089:8089
#      - 15000:15000
#      - 10667:10667
#      - 10668:10668/udp
#    healthcheck:
#      test: [ 'CMD', 'curl', '-f', 'https://localhost:8000' ]
#      interval: 5s
#      timeout: 5s
#      retries: 20
  #############################################################################################
  ###                                 POSTGRESQL                                            ###
  #############################################################################################
  postgresql:
    image: postgres:12.8
    environment:
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRES_DB=${POSTGRESQL_DB}
    volumes:
      - postgresql-data:/var/lib/pgsql/data

  #############################################################################################
  ###                                 SONARQUBE                                             ###
  #############################################################################################
  sonarqube:
    image: sonarqube:9.0.1-community
    environment:
      - SONARQUBE_JDBC_PASSWORD=${POSTGRESQL_PASSWORD}
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgresql/sonar
      - SONARQUBE_JDBC_USERNAME=${POSTGRESQL_USER}
      - SONAR_FORCEAUTHENTICATION=true
    ports:
      - "9000:9000"
    volumes:
      - ./sonarqube/conf:/opt/sonarqube/conf
      - sonar-data:/opt/sonarqube/data
      - sonar-logs:/opt/sonarqube/logs
      - sonar-temp:/opt/sonarqube/temp
      - sonar-plugins:/opt/sonarqube/extensions/plugins
    restart: always

  #############################################################################################
  ###                                 SONARQUBE INIT                                        ###
  #############################################################################################
  sonarqube-init:
    build:
      context: ./sonarqube
    environment:
      - PGPASSWORD=${POSTGRESQL_PASSWORD}
      - SONAR_TOKEN=${SONAR_TOKEN}
      - SONAR_PROJECT_KEY=${SONAR_PROJECT_KEY}
      - SONAR_PROJECT_NAME=${SONAR_PROJECT_NAME}
      - SONAR_PROJECT_API_TOKEN=${SONAR_PROJECT_API_TOKEN}
      - SONAR_PASSWORD=${SONAR_PASSWORD}
      - SONAR_URL=http://sonarqube:9000
    volumes:
      - sonar-plugins:/opt/sonarqube/extensions/plugins
      - sonar-logs:/opt/logs
  scss-api:
    build:
      context: .
    environment:
      - BASIC_AUTH_USER=${BASIC_AUTH_USER}
      - BASIC_AUTH_PASS=${BASIC_AUTH_PASS}
      - SCSS_HOST=${SCSS_HOST}
    ports:
      - 8080:8080

volumes:
  postgresql-data:
  sonar-data:
  sonar-logs:
  sonar-temp:
  sonar-plugins:
