security:
  basic-auth:
    password: ${BASIC_AUTH_PASS}
    username: ${BASIC_AUTH_USER}
scss:
  host: http://127.0.0.1/
  username: ${BASIC_AUTH_PASS}
  password: ${BASIC_AUTH_USER}
  ords-read-timeout: ${ORDS_READ_TIMEOUT:120}
